# Generated by Django 5.2.17 on 2026-08-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region",
            old_name="name",
            new_name="title",
        ),
    ]
