# Generated by Django 5.2.17 on 2026-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_name_region_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
