# Generated by Django 5.2.17 on 2026-08-11 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_region_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="regions/"),
        ),
    ]
